# D Joubert Innoventix Consulting 27 October 2016

import local_paths

SERVER_LOG_DIR = local_paths.SERVER_LOG_DIR
SESSION_ROOT_DIR = local_paths.SESSION_ROOT_DIR
DISPLAY_DOWNLOAD_DIR = local_paths.DISPLAY_DOWNLOAD_DIR

# gphoto2 canon config vars
CANON_EOS_6D_CAPTURE_TARGET_MEMORY = 0
CANON_EOS_6D_CAPTURE_TARGET_SD_CARD = 1

CANON_EOS_6D_SHUTTER_SPEED_1_OVER_2500 = 49
CANON_EOS_6D_SHUTTER_SPEED_1_OVER_640 = 43
CANON_EOS_6D_SHUTTER_SPEED_1_OVER_4 = 21



class TRICAP_CAMS_MANAGER_STATES:
    STOPPED, STARTED, ERROR_NO_CAMS = range(3)
    MAX = 2
    MIN = 0


class ALTIMETER_STATE:
    NOT_CONNECTED, CONNECTED, MEASURING, ERROR = range(4)
    MAX = 2
    MAX = 0


class BUTTON_CODES:
    START, STOP, TEST = range(3)
    MAX = 2
    MIN = 0
