SERVER_LOG_DIR = 'C:/Projects/IndlovuCode/tricap/Code/tricap/'
DISPLAY_DOWNLOAD_DIR = 'C:/Projects/IndlovuCode/tricap/Code/tricap/tmp'
SESSION_ROOT_DIR = 'C:/temp'
WORKING_OS = 'windows'
DUMMY_IMAGE_PATH = 'C:/Users/Public/Pictures/Sample Pictures/Jellyfish.jpg'
CONFIG_FP = 'C:/Projects/IndlovuCode/tricap/Code/tricap/init_config.txt'
DEFAULT_CONFIG_FP = 'C:/Projects/IndlovuCode/tricap/Code/tricap/init_config_default.txt'
