syntax = "proto3";

// cd /home/radxa/tricap
// protoc --python_out=serial_comms/out tricap.proto

// ./protobuf/node_modules/.bin/pbjs -t static-module -w commonjs -o protobuf/out/tricap_pb.js tricap.proto
// ./protobuf/node_modules/.bin/pbts -o protobuf/out/tricap_pb.d.ts protobuf/out/tricap_pb.js

package tricap;

message IpAddress {
  optional string ip = 1;
}

message WifiSetup {
  optional string ssid = 1;
  optional string password = 2;
}

message Message {
  enum MessageType {
    IP_ADDRESS = 0;
    WIFI_SETUP = 1;
  }

  optional MessageType msgType = 1;

  optional IpAddress ip = 2;
  optional WifiSetup wifi = 3;
}
